const projects = [
  {id:'sms',icon:'✉',name:'مدیریت پیامک',type:'ارتباطات سازمانی',title:'مرکز مدیریت پیامک',desc:'ارسال هدفمند، گزارش تحویل و پیگیری فعالیت‌ها در یک پنل.',tags:['Flask','داشبورد مدیریتی'],pill:'پیامک',metrics:[['ارسال امروز','۲٬۸۴۰','پیام','↑ ۱۲٪ نسبت به دیروز'],['تحویل موفق','۹۸٫۶','٪','عملکرد پایدار'],['در صف ارسال','۱۲۶','پیام','۳ کمپین فعال'],['اعتبار پنل','۴۸٬۲۰۰','پیامک','به‌روزرسانی آزمایشی']],rows:[['کمپین یادآوری','همراهان نمونه','۱٬۲۴۰','۱٬۲۲۸','ارسال‌شده'],['اطلاع‌رسانی رویداد','اعضای نمونه','۸۶۰','۸۴۲','در حال ارسال'],['پیام خوشامد','کاربران تازه','۴۲۰','۴۲۰','ارسال‌شده'],['نظرسنجی خدمات','مخاطبان نمونه','۳۲۰','۳۱۰','زمان‌بندی‌شده']],events:[['گزارش تحویل آماده شد','کمپین یادآوری','۰۹:۴۲'],['کارزار جدید زمان‌بندی شد','اطلاع‌رسانی رویداد','۰۹:۱۸'],['فهرست مخاطبان به‌روزرسانی شد','گروه کاربران نمونه','دیروز']],button:'ارسال پیام آزمایشی'},
  {id:'budget',icon:'◈',name:'بودجه‌ریزی عملیاتی',type:'مدیریت مالی',title:'برنامه‌ریزی و پایش بودجه',desc:'درخواست، بررسی و پایش تخصیص‌ها در چرخه‌ی بودجه‌ی واحدها.',tags:['Laravel','Vue 3','Inertia'],pill:'بودجه',metrics:[['بودجه مصوب','۸٫۴','میلیارد','دوره مالی جاری'],['مصرف‌شده','۵٫۷','میلیارد','۶۸٪ از تخصیص'],['در انتظار بررسی','۷','درخواست','۲ مورد نیازمند اقدام'],['مانده قابل تخصیص','۲٫۷','میلیارد','تا پایان دوره']],rows:[['تجهیزات فناوری','فناوری اطلاعات','۳۲۰','تجهیزات','در انتظار'],['آموزش تیمی','سرمایه انسانی','۱۸۰','آموزش','در انتظار'],['نگهداشت شبکه','فناوری اطلاعات','۹۵','عملیات','تأییدشده'],['رویداد فصلی','ارتباطات','۲۴۰','رویداد','در انتظار']],events:[['درخواست جدید ثبت شد','تجهیزات فناوری','۱۰:۲۱'],['تخصیص دوره به‌روزرسانی شد','واحد ارتباطات','دیروز'],['گزارش ماهانه آماده است','دوره مالی جاری','دیروز']],button:'ثبت درخواست آزمایشی'},
  {id:'food',icon:'✳',name:'عملیات و غذای روزانه',type:'خدمات و موجودی',title:'میزکار عملیات غذا',desc:'برنامه‌ی روزانه، موجودی مواد و سفارش‌های مجموعه در یک نگاه.',tags:['React','Laravel'],pill:'عملیات غذا',metrics:[['سفارش امروز','۱۸۴','سفارش','۱۲ سفارش جدید'],['آماده تحویل','۲۸','سفارش','زمان تحویل ۱۲:۳۰'],['موجودی مواد','۸۶','٪','۳ قلم نیازمند بررسی'],['رضایت این هفته','۴٫۷','از ۵','بر اساس بازخورد نمونه']],rows:[['خوراک سبزیجات','ناهار امروز','۷۲','موجودی کافی','فعال'],['مرغ زعفرانی','ناهار امروز','۶۴','موجودی محدود','فعال'],['سوپ روز','پیش‌غذا','۴۸','موجودی کافی','فعال'],['سالاد فصل','کنار غذا','۳۲','در حال آماده‌سازی','فعال']],events:[['موجودی برنج ثبت شد','انبار آشپزخانه','۱۰:۰۴'],['برنامه ناهار منتشر شد','منوی امروز','۰۹:۳۰'],['بازخورد جدید دریافت شد','سفارش نمونه','دیروز']],button:'ثبت سفارش آزمایشی'},
  {id:'arbitration',icon:'⚖',name:'پیگیری درخواست‌ها',type:'خدمات و پرونده‌ها',title:'درگاه پیگیری درخواست',desc:'ثبت اولیه، مشاهده‌ی وضعیت و دنبال‌کردن مراحل رسیدگی به درخواست‌ها.',tags:['Django REST','Vue 3'],pill:'درخواست‌ها',metrics:[['درخواست‌های باز','۲۴','مورد','در ۴ مرحله رسیدگی'],['نیازمند تکمیل','۵','مورد','مدرک یا توضیح بیشتر'],['در حال بررسی','۱۲','مورد','میانگین ۳ روز کاری'],['پاسخ‌داده‌شده','۴۱','مورد','در بازه‌ی انتخابی']],rows:[['درخواست مشاوره','پرونده نمونه ۱۰۲','ثبت اولیه','امروز','در حال بررسی'],['تکمیل مدارک','پرونده نمونه ۰۹۸','مدارک','دیروز','نیازمند اقدام'],['پیگیری درخواست','پرونده نمونه ۰۹۱','بررسی','۲ روز پیش','در حال بررسی'],['درخواست راهنمایی','پرونده نمونه ۰۸۴','پاسخ','این هفته','پاسخ‌داده‌شده']],events:[['درخواست جدید ثبت شد','پرونده نمونه ۱۰۲','۱۰:۱۲'],['مدرک تکمیلی دریافت شد','پرونده نمونه ۰۹۸','دیروز'],['پاسخ مرحله اول آماده شد','پرونده نمونه ۰۸۴','دیروز']],button:'ثبت درخواست آزمایشی'},
  {id:'portal',icon:'⌂',name:'پورتال خدمات سازمانی',type:'درگاه خدمات',title:'پورتال یکپارچه خدمات',desc:'دسترسی روشن و ساده به خدمات، اطلاعیه‌ها و درخواست‌های اعضا.',tags:['TypeScript','Supabase'],pill:'پورتال',metrics:[['خدمات فعال','۲۸','خدمت','در ۶ دسته'],['بازدید امروز','۱٬۲۰۶','بازدید','↑ ۸٪ این هفته'],['درخواست باز','۳۶','درخواست','۹ مورد تازه'],['میانگین پاسخ','۱٫۸','روز','در محدوده هدف']],rows:[['گواهی و استعلام','خدمات ثبتی','آنلاین','راهنمای مرحله‌ای','فعال'],['مشاوره تخصصی','پشتیبانی','درخواست','پیگیری در پنل','فعال'],['رزرو فضای جلسه','امکانات','تقویم','ظرفیت به‌روز','فعال'],['دوره‌های آموزشی','یادگیری','ثبت‌نام','برنامه‌ی ماهانه','فعال']],events:[['خدمت تازه اضافه شد','راهنمای عضویت','۱۰:۳۰'],['اطلاعیه برنامه‌ی ماهانه منتشر شد','رویدادهای نمونه','دیروز'],['درخواست پاسخ داده شد','خدمات اعضا','دیروز']],button:'ثبت درخواست آزمایشی'}
];

let activeId='sms';
let requestNumber=103;
let reservedMeal=false;
let stockAdded=false;
let budgetRequestAdded=false;
const faNumber=value=>new Intl.NumberFormat('fa-IR').format(value);
const nav=document.querySelector('#project-nav');
const showcase=document.querySelector('#showcase');

function renderNav(){
  nav.innerHTML=projects.map(p=>`<button class="project-link ${p.id===activeId?'active':''}" data-project="${p.id}" aria-pressed="${p.id===activeId}"><span class="project-icon">${p.icon}</span><span><strong>${p.name}</strong><small>${p.type}</small></span></button>`).join('');
}

function metricCards(p){return p.metrics.map((m,i)=>`<div class="metric-card"><div class="metric-label"><span>${m[0]}</span><span>${['↗','◷','⌁','◌'][i]}</span></div><div class="metric-value">${p.id==='budget'&&i===2&&budgetRequestAdded?'۸':m[1]}<small>${m[2]}</small></div><div class="metric-foot ${i===0?'trend':''}">${m[3]}</div></div>`).join('')}
function activityList(events){return events.map((e,i)=>`<div class="activity"><i class="activity-dot" style="background:${i===0?'#91b56d':'#c3cfba'}"></i><span><b>${e[0]}</b><small>${e[1]}</small></span><time>${e[2]}</time></div>`).join('')}
function genericChart(p){let caption=p.id==='budget'?'مصرف از تخصیص':p.id==='food'?'تکمیل سفارش‌ها':p.id==='arbitration'?'روند رسیدگی':p.id==='portal'?'استفاده از خدمات':'تحویل موفق';return `<div class="panel mini-chart"><div class="panel-head"><h3>${caption}</h3><span>۷ روز اخیر</span></div><div class="chart-value">${p.id==='sms'?'۹۸٫۶٪':p.id==='budget'?'۶۸٪':p.id==='food'?'۸۴٪':p.id==='arbitration'?'۷۶٪':'۸۹٪'}</div><div class="chart-caption">نسبت به هفته‌ی گذشته <b class="trend">↑ ۶٫۴٪</b></div><div class="bars" aria-label="نمودار هفتگی">${[36,58,46,76,52,88,67,96,62,77,89,72].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><div class="bar-labels"><span>SAT</span><span>MON</span><span>WED</span><span>FRI</span></div></div>`}
function panelTable(p){let cols=p.id==='sms'?['عنوان کمپین','گروه مخاطب','ارسال','تحویل','وضعیت']:p.id==='budget'?['عنوان درخواست','واحد','مبلغ (میلیون)','دسته','وضعیت']:p.id==='food'?['عنوان غذا','دسته','سفارش','وضعیت موجودی','وضعیت']:p.id==='arbitration'?['نوع درخواست','شناسه نمایشی','مرحله','آخرین تغییر','وضعیت']:['عنوان خدمت','دسته','روش دریافت','جزئیات','وضعیت'];let rows=[...p.rows];if(p.id==='budget'&&budgetRequestAdded)rows.unshift(['درخواست آزمایشی جدید','واحد نمونه','۱۲۵','عملیات','در انتظار']);if(p.id==='arbitration'&&requestNumber>103)rows.unshift(['درخواست راهنمایی','پرونده نمونه '+requestNumber,'ثبت اولیه','همین حالا','ثبت‌شده']);if(p.id==='food'&&stockAdded)rows[1]=['مرغ زعفرانی','ناهار امروز','۶۴','موجودی به‌روزرسانی شد','فعال'];return `<div class="panel"><div class="panel-head"><h3>${p.id==='budget'?'درخواست‌های اخیر':p.id==='food'?'منوی امروز':p.id==='arbitration'?'آخرین درخواست‌ها':p.id==='portal'?'خدمات پرکاربرد':'فعالیت کمپین‌ها'}</h3><span>مشاهده همه&nbsp; ↗</span></div><div class="table-scroll"><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.map((r,ri)=>`<tr>${r.map((c,ci)=>`<td>${ci===0?`<strong>${c}</strong>`:ci===r.length-1?`<span class="status ${['در انتظار','نیازمند اقدام','در حال بررسی','ثبت‌شده'].includes(c)?'pending':''}">${c}</span>`:c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function extraPanel(p){if(p.id==='budget')return `<div class="panel"><div class="panel-head"><h3>درخواست در انتظار</h3><span>۳ مورد</span></div><div class="activity-list">${[['تجهیزات فناوری','۳۲۰ میلیون · فناوری اطلاعات'],['آموزش تیمی','۱۸۰ میلیون · سرمایه انسانی'],['رویداد فصلی','۲۴۰ میلیون · ارتباطات']].map((x,i)=>`<div class="activity"><i class="activity-dot"></i><span><b>${x[0]}</b><small>${x[1]}</small></span><button class="table-action approve" data-index="${i}">بررسی</button></div>`).join('')}</div></div>`;
if(p.id==='food')return `<div class="panel"><div class="panel-head"><h3>خدمات سریع</h3><span>امروز · ۱۲:۳۰</span></div><div class="meal-list"><div class="meal-row"><span>رزرو ناهار<small>خوراک روز + نوشیدنی</small></span><span class="status ${reservedMeal?'':'neutral'}">${reservedMeal?'رزرو شد':'ظرفیت باز'}</span></div><div class="meal-row"><span>برنج ایرانی<small>موجودی انبار</small></span><span>${stockAdded?'۲۴':'۱۸'} کیلو</span></div><div class="meal-row"><span>مرغ تازه<small>موجودی انبار</small></span><span>${stockAdded?'۳۱':'۲۵'} کیلو</span></div></div><div class="action-row" style="padding:0 14px 12px"><button class="button button-soft" data-action="reserve">${reservedMeal?'رزرو ثبت شد':'رزرو غذای امروز'}</button><button class="button button-soft" data-action="stock">ثبت ورود موجودی</button></div></div>`;
if(p.id==='arbitration')return `<div class="panel"><div class="panel-head"><h3>پیگیری پرونده</h3><span>شناسه نمایشی</span></div><div class="ticket"><div class="ticket-top"><b>پرونده نمونه ${requestNumber}</b><span class="status ${requestNumber>103?'pending':''}">${requestNumber>103?'ثبت اولیه':'در حال بررسی'}</span></div><p>${requestNumber>103?'درخواست آزمایشی با موفقیت ثبت شد.':'آخرین به‌روزرسانی: کارشناس پرونده تعیین شد.'}</p><div class="progress-track"><i style="width:${requestNumber>103?'22':'58'}%"></i></div><div class="ticket-meta"><span>ثبت ← بررسی ← پاسخ</span><span>اطلاعات نمایشی</span></div></div></div>`;
if(p.id==='portal')return `<div class="panel"><div class="panel-head"><h3>دسترسی سریع</h3><span>درگاه نمونه</span></div><div class="portal-links">${[['گواهی و استعلام','↗'],['مشاوره و پشتیبانی','↗'],['رویدادهای پیش‌رو','↗'],['راهنمای اعضا','↗']].map(x=>`<a href="#" class="portal-link" data-action="portal-link"><span>${x[0]}</span><span>${x[1]}</span></a>`).join('')}</div></div>`;
return `<div class="panel"><div class="panel-head"><h3>رویدادهای اخیر</h3><span>امروز</span></div><div class="activity-list">${activityList(p.events)}</div></div>`}
function render(){const p=projects.find(x=>x.id===activeId);renderNav();const index=projects.indexOf(p)+1;document.querySelector('#current-index').textContent=`${String(index).padStart(2,'0')} / 05`;const rowCount=p.id==='sms'?['۲٬۸۴۰ پیام ارسال‌شده','به‌روزرسانی زنده']:p.id==='budget'?[budgetRequestAdded?'۸ درخواست فعال':'۷ درخواست فعال','چرخه مالی جاری']:p.id==='food'?['۱۸۴ سفارش امروز','منوی روزانه']:p.id==='arbitration'?['۲۴ درخواست باز','پیگیری شفاف']:['۲۸ خدمت فعال','درگاه سازمانی'];showcase.innerHTML=`<div class="demo-head"><div class="demo-heading"><span class="demo-big-icon">${p.icon}</span><div class="demo-title"><h2>${p.title}</h2><p>${p.desc}</p></div></div><div class="demo-pills"><span class="pill live">● محیط نمایشی</span>${p.tags.map(t=>`<span class="pill">${t}</span>`).join('')}</div></div><div class="dash-toolbar"><span class="crumb">میزکار / <b>${p.pill}</b></span><div class="toolbar-actions"><span class="date-chip">امروز، ۴ مهر ۱۴۰۵</span><button class="button button-primary" data-action="primary">${p.button}<span>＋</span></button></div></div><div class="metric-grid">${metricCards(p)}</div><div class="demo-grid">${panelTable(p)}<div class="side-stack">${genericChart(p)}${extraPanel(p)}</div></div><div class="action-row"><span class="action-hint">${rowCount[0]} · ${rowCount[1]} · همه اطلاعات ساختگی است</span></div>`}
let toastTimer;
function toast(message){let el=document.querySelector('.workspace-toast');if(!el){el=document.createElement('div');el.className='workspace-toast';el.setAttribute('role','status');document.body.append(el)}el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
nav.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;activeId=button.dataset.project;render()});
showcase.addEventListener('click',e=>{const approve=e.target.closest('.approve');if(approve){approve.textContent='تأیید شد';approve.disabled=true;approve.closest('.activity').querySelector('.activity-dot').style.background='#8db36a';toast('تأیید نمونه ثبت شد؛ تغییری در سامانه واقعی انجام نشد.');return}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='primary'){if(activeId==='food'){reservedMeal=true;render();toast('سفارش آزمایشی ثبت شد.')}else if(activeId==='arbitration'){requestNumber++;render();toast(`درخواست نمایشی ${requestNumber} ثبت شد.`)}else if(activeId==='budget'){budgetRequestAdded=true;render();toast('درخواست بودجه‌ی آزمایشی ثبت شد.')}else if(activeId==='portal'){toast('درخواست آزمایشی آماده ثبت است.')}else{toast('پیام آزمایشی در پیش‌نمایش صف ارسال قرار گرفت.')}return}if(action==='reserve'){reservedMeal=true;render();toast('رزرو ناهار آزمایشی انجام شد.');return}if(action==='stock'){stockAdded=true;render();toast('ورود موجودی نمایشی ثبت شد.');return}if(action==='portal-link'){e.preventDefault();toast('این بخش در نسخه نمایشی قابل مشاهده است.')}});
render();
